LZO_RLE->LZ4->ZSTD->LZO->FAIL

diff --git a/usr/lib/initcpio/hooks/ramroot b/usr/lib/initcpio/hooks/ramroot
--- a/usr/lib/initcpio/hooks/ramroot
+++ b/usr/lib/initcpio/hooks/ramroot
@@ -167,23 +167,29 @@ run_hook() {
         sleep 1
     fi
     sleep 1
-    zram_device="$(zramctl -f -s ${zram}M -a lz4)"
-    # ERROR: error initializing with lz4:
+    zram_device="$(zramctl -f -s ${zram}M -a lzo_rle)"
+    # ERROR: error initializing with lzo_rle:
     if [ $? -ne 0 ]; then
         printf '\e[1;33m==> NOTICE: \e[1;37m%s\e[0;37m\n' \
-            'cannot initialize with lz4, trying zstd'
-        zram_device="$(zramctl -f -s ${zram}M -a zstd)"
-         # ERROR: error initializing with zstd:
+            'cannot initialize with lzo_rle, trying lz4'
+        zram_device="$(zramctl -f -s ${zram}M -a lz4)"
+         # ERROR: error initializing with lz4:
         if [ $? -ne 0 ]; then
             printf '\e[1;33m==> NOTICE: \e[1;37m%s\e[0;37m\n' \
-                'cannot initialize with zstd, trying lzo'
-            zram_device="$(zramctl -f -s ${zram}M -a lzo)"
-            # FAIL: cannot create zram device with preferred algorithms
+                'cannot initialize with lz4, trying zstd'
+            zram_device="$(zramctl -f -s ${zram}M -a zstd)"
+            # ERROR: error initializing with zstd:
             if [ $? -ne 0 ]; then
-                printf '\e[1;31m==> FAILED: \e[1;37m%s\e[0;37m\n' \
-                    'cannot initialize zram device'
-                sleep 2
-                return 1
+                printf '\e[1;33m==> NOTICE: \e[1;37m%s\e[0;37m\n' \
+                    'cannot initialize with zstd, trying lzo'
+                zram_device="$(zramctl -f -s ${zram}M -a lzo)"
+                # FAIL: cannot create zram device with preferred algorithms
+                if [ $? -ne 0 ]; then
+                    printf '\e[1;31m==> FAILED: \e[1;37m%s\e[0;37m\n' \
+                        'cannot initialize zram device'
+                    sleep 2
+                    return 1
+                fi
             fi
         fi
     fi
